# Generated by Django 3.2.25 on 2025-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
