# Generated by Django 3.2.25 on 2025-12-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order of the day (1 = first day, 2 = second day, etc.)')),
                ('title', models.CharField(help_text='Day title (e.g. Day 1, Opening Day)', max_length=100)),
                ('date', models.DateField()),
                ('details', models.TextField(help_text='Summary of activities for this day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.event')),
            ],
            options={
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'order')},
            },
        ),
    ]
