# Generated by Django 3.2.25 on 2025-12-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('event', 'date')},
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='order',
        ),
    ]
