# Generated by Django 3.2.25 on 2025-12-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Affiliaton',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
