# Generated by Django 3.2.25 on 2025-12-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251217_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
