# Generated by Django 3.2.25 on 2025-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_topic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Affiliaton',
            new_name='affiliation',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('author', 'Author'), ('participant', 'Participant')], max_length=20, null=True),
        ),
    ]
