# Generated by Django 3.2.25 on 2025-12-23 19:16

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20251223_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('paper_type', models.CharField(choices=[('oral', 'Oral'), ('poster', 'Poster'), ('workshop', 'Workshop')], max_length=20)),
                ('pdf_file', models.FileField(null=True, upload_to=core.models.paper_pdf_file_path)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['event', 'status'], name='core_paper_event_i_6cc9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['author'], name='core_paper_author__1308f6_idx'),
        ),
    ]
